apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: synergychat-web
  name: synergychat-web
spec:
  selector:
    matchLabels:
      app: synergychat-web
  template:
    metadata:
      labels:
        app: synergychat-web
    spec:
      containers:
      - image: lanecwagner/synergychat-web:latest
        name: synergychat-web
        envFrom:
          - configMapRef:
              name: synergychat-web-configmap
